### ISSUE TITLE
Added jupyterlab-vim to environment.yml

### ISSUE THREAD

**Issue by nicole-brewer** [nicole-brewer/jupyterlab-ide#21]
## Steps 

- [x] run `git pull` before you get started making branches or anything else. If you are the second one to walk through this exercise, you may get a merge conflict if you forget this step. That's because you are both editing the same file, so if you forget to pull the changes the other one made to the remote, github won't know what to do when you both ask it to change `environment.yml` in different ways
- [x] Make a new a dev branch, for David "devdav", using `git branch devdav`
- [x] Switch to the branch with `git checkout devdav`
- [x] Add to the environment.yml file `jupterylab-vim` extension.
- [x] Use `git add binder/environment.yml` to stage the change
- [x] Commit the changes with `git commit -m "message"`
- [x] Push the changes with `git push origin devdav` (creating a new branch)
- [x] Add commentary on changes

**Comment by Dcosthephalump** [comment]
Resolved the issue using the steps laid out in the issue.
