### ISSUE TITLE
Double check what extensions are in the README.md versus the environment.yml [45, 30, 30]

### ISSUE THREAD

**Issue by Dcosthephalump** [nicole-brewer/jupyterlab-ide#25]

**Comment by namitasshah** [comment]
6/20: 
- Added -latex, -sidecar, -code_formatter to the environment file. 
- Spellchecker and -vim library are on our separate branches that we created when we did the tutorial exercise 
-Included in envmt.yml file but not in README file is jupyterlab-unfold and jupyterlab-git
