### ISSUE TITLE
Change repository name / fix Binder link

### ISSUE THREAD

**Issue by nicole-brewer** [nicole-brewer/jupyterlab-ide#5]
## The short of it

If we change the repository name back to `jupyterlab-ide`, the binder badge link should work again. 

@Dcosthephalump could you...
- [x] change the repository name to `jupyterlab-ide`
- [x] #6
- [x] make sure the Binder link works again
- [x] If that fixes it, make a comment below that says such and close the issue
- [x] If it is still broken for some reason, create and issue about what the error is and how you think you might fix it

## Thinking behind this

The reason the binder doesn't work is because I changed the repository name and didn't update the binder badge to match. But I think we should work on the name together. I was thinking that awesome-jupyterlab already exists. Our repository is still trying to be a comprehensive list but the scope is smaller. We are only concerned with features that improve the development environment. I think the repo name needs to reflect that. If we had a ton of space, the most straight forward name would be `awesome-jupyterlab-development-environment`. But we also don't want a name that is too long. I used to call the repo `jupyterlab-ide`, but I'm concerned that not everyone will be familiar with the term. Then again, maybe we should take a step back...

**Who is our audience?** Is it developers or scientists.... or both? I think for any educational material it's important to figure this out before writing anything. I think it may be easier to create this tutorial for a software developer audience. That way, we can use terms like IDE, tab completion, etc., without having to explain what each of those are. If we wanted to expand the scope of this work, and include scientists, we could do that in another branch or another repository and adding the additional background info the scientists would need to digest the info.

**Comment by namitasshah** [comment]
Link is fixed!
