### ISSUE TITLE
Check if extensions in README.md are still important

### ISSUE THREAD

**Issue by Dcosthephalump** [nicole-brewer/jupyterlab-ide#54]
Some extensions in the README.md are not in the environment.yml

- [jupyterlab-latex](https://github.com/jupyterlab/jupyterlab-latex)
- [jupyterlab-sidecar](https://github.com/jupyter-widgets/jupyterlab-sidecar)
- [jupyterlab_code_formatter](https://github.com/ryantam626/jupyterlab_code_formatter)

Some extensions in the environment.yml are not in the README.md

- [jupyterlab-unfold](https://github.com/jupyterlab-contrib/jupyterlab-unfold)
- [jupyterlab-git](https://github.com/jupyterlab/jupyterlab-git)

Do either of these files need to have updates?

**Comment by nicole-brewer** [comment]
We want to leave the extensions in our list even if they aren't included in our tutorial. That said, we should probably make sure that we distinguish between the two in the README. Maybe we should have a two different headings. One that says something like "Extensions in this repo" and "Other extensions" or something like that.

Sidenote, maybe for "Extensions in this repo" we should also put links to the notebooks that cover them, like this: 
- [jupyterlab-lsp](https://github.com/krassowski/jupyterlab-lsp) [(notebook)](link_to_notebook) [(video)](link_to_namitas_tutorial_video)
