### ISSUE TITLE
High-level items for 1st milestone

### ISSUE THREAD

**Issue by nicole-brewer** [nicole-brewer/jupyterlab-ide#8]
- [ ] #9
- [ ] #10
- [ ] #14
- [ ] #13
- [ ] #12
- [ ] #11
- [ ] #5

**Comment by Dcosthephalump** [comment]
These different items are each measurable items that, when completed, signify a concrete step towards achieving the milestone. This means that they should each be kept as their own issues to make completion easier to track.

**Comment by nicole-brewer** [comment]
@namitasshah and I need to attach the issue above to milestones
